theme: jekyll-theme-minimal
title: Chaitanya C Belgaumkar | Data Analyst
logo: SAVE_20240418_191632-fotor-202409261412.jpeg
description: Data Analytics Projects, SQL, Power BI, Excel, and Business Intelligence Portfolio
